#!/bin/bash
# Creates a tiled montage of all the avatars in the avatars directory
# Usage: script/create [optional additional montage options to customize]

montage avatars/*.png -background black "$@" montage.png 
